(in-package #:cffi-wordnet)

(defparameter +noun+ NOUN)
(defparameter +verb+ VERB)
(defparameter +adjective+ ADJ)
(defparameter +adverb+ ADV)
(defparameter +satellite+ SATELLITE)
(defparameter +all-senses+ ALLSENSES)
(defparameter +synonyms+ SYNS)
(defparameter +freq+ FREQ)
(defparameter +frames+ FRAMES)
(defparameter +coords+ COORDS)
(defparameter +relatives+ RELATIVES)
(defparameter +meronym+ HMERONYM)
(defparameter +holonym+ HHOLONYM)
(defparameter +hypernym+ HYPERPTR)
